apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: developer
  POSTGRES_PASSWORD: dev123
  POSTGRES_DB: blog_app
  DB_HOST: fullstack-postgres
  DB_DRIVER: postgres
  API_SECRET: 98hbun98h
  DB_USER: developer
  DB_PASSWORD: dev123
  DB_NAME: blog_app
  DB_PORT: "5432"